# NUMPY LIBRARY

**Numpy arrays come in two flavors **  

1. **Vectors:** strictly 1D arrays  
2. **Matrices:** 2-dimensional  
    - Should note a matrix can still have only one row or one column  
    - Denoted by double brackets
    
**Why you want to convert Python lists to NumPy arrays:  **
- More compact than python lists (less memory)
- More efficient  
- More convenient with vector and matrix operations/computing  
- Built in functions (statistics, histograms,etc)
- Speed
    
### Creating Arrays by Casting a List

In [162]:
# Create list
my_list = [1,2,3]

# Cast python list to 1 dimensional numpy array
import numpy as np
np.array(my_list)

array([1, 2, 3])

In [163]:
# Create list of lists
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

# Cast list of lists to a two dimensional array.Two sets of brackets indicate this is a two dimensional array.
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [170]:
# More common way to quickly geneate an array, similar to python's range function
np.arange(0,10,2) # Third argumnt is the step size

array([0, 2, 4, 6, 8])

In [166]:
# Generate array of all zeros
np.zeros(3)

array([ 0.,  0.,  0.])

In [168]:
# Generate two dimensional matrix using tuples
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [169]:
# Linspace uses third argument as the number of points you want
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [173]:
# Create identify matrix.two dimensional square matrix, number of rows is the same as number of columns and diagonal of ones. useful for linear algebra problems
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

### Creating Arrays with Built-In Rand Functions

In [176]:
# Create one dimensional array of random numbers from a uniform distribution 0 to 1
np.random.rand(5)

array([ 0.29196759,  0.26105212,  0.58233309,  0.12037359,  0.05191316])

In [177]:
# Create 5x5 matrix of random numbers from a uniform distribution 0 to 1
np.random.rand(5,5)

array([[ 0.38761197,  0.60234934,  0.52494045,  0.67476831,  0.83521657],
       [ 0.19396468,  0.15400565,  0.56173788,  0.32278135,  0.18438814],
       [ 0.97825407,  0.02587986,  0.17780609,  0.9148869 ,  0.29836927],
       [ 0.37697747,  0.50578518,  0.21990663,  0.33234242,  0.86459501],
       [ 0.45656233,  0.41347845,  0.21339653,  0.07060457,  0.5746209 ]])

In [178]:
# Create array of random numbers from a stardard normal distribution centered around 0
np.random.randn(2)

array([ 1.39165968,  0.09135831])

In [180]:
# Create array of random numbers from a stardard normal distribution centered around 0
np.random.randn(4,4)

array([[-1.01363863, -0.01175273, -0.59360067, -0.92489113],
       [ 0.63612071,  0.60483885,  0.4708122 , -0.58512604],
       [ 1.52559863,  0.10156385,  0.28881798,  0.77212452],
       [-1.60691117, -1.35041257, -0.41543116, -0.48286673]])

In [181]:
# Create array of random integers from a low number (inclusive) to high number (exclusive)
np.random.randint(1,100,10) #3rd argument is the particular number of random integers you want 

array([19, 13, 56, 20, 13,  3, 81, 40, 84, 92])

### Useful Array Methods

In [183]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [185]:
ranarr = np.random.randint(0,50,10)
ranarr

array([10,  9, 43, 14, 27,  0, 33, 39, 36, 27])

In [186]:
# Reshape array to 5 x 5 matrix
arr.reshape(5,5)# pass in new dimensions, # rows and # columns, you want

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [187]:
# Find max
ranarr.max()

43

In [188]:
# Fin min value
ranarr.min()

0

In [189]:
# Find location value of max
ranarr.argmax()

2

In [190]:
# Find location of min
ranarr.argmin()

5

### Attributes
When calling attributes, do not need parenthesis

In [193]:
arr.shape

(25,)

In [194]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [195]:
# Find data type of array
arr.dtype

dtype('int32')

In [196]:
from numpy.random import randint
randint(2,10)

3

### Indexing and Selection

In [3]:
# Create an array of 11 elements from 0 to 10
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# Return value at index 8
arr[8]

8

In [5]:
# Use slicing
arr[1:5] # return all values from start index all the way up to (but not including) stop index

array([1, 2, 3, 4])

In [7]:
# Slice everything before index 6
arr[:6] #same as [0:6], w slice notation grab one more than you actually need

array([0, 1, 2, 3, 4, 5])

In [8]:
# Everything beyond index 5
arr[5:] 

array([ 5,  6,  7,  8,  9, 10])

In [11]:
# Broadcast value to first 5 digits
arr[0:5] = 100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [16]:
# Create copy of an array
arr_copy = arr.copy()
arr_copy[:]=100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

### Indexing 2D Array (Matrices)

In [18]:
import numpy as np
arr_2d = np.array([[5,10,15],[20,25,30],[30,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 40, 45]])

In [19]:
# Double bracket format to grab elements from 2D array (matrix)
arr_2d[2][1] # , row index, column index


10

In [20]:
# Single bracket with comma notation to grab elements from 2D array, recommended way!
arr_2d[2,1]

40

In [22]:
# Grab top right corner
arr_2d[:2,1:] 

array([[10, 15],
       [25, 30]])

### Conditional Selection

In [24]:
arr = np.arange(1,11)

In [26]:
# Create boolean array using comparison operator
bool_arr =arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [27]:
# Use boolean array to index (conditionally select) elements of the original array where the boolean array was true
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [29]:
# One step conditional selection
arr[arr<3]

array([1, 2])

In [31]:
# Create 2D matrix of 50 integers starting at 0
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [32]:
arr_2d[1:3,] # Stop index, grab one more than you actually need

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

# **Basic Operations**

### ** Array with Array**

In [35]:
import numpy as np

# Create array of 11 digits from 0 to 10
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
# Add two arrays together on an element by element basis
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### **Array with Scalers (Single Numbers)**

In [38]:
# Add 100 to every element in the array
arr + 100

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

 ### Universal Array Functions


In [39]:
# Take square root of every element in the array
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [40]:
# Find exponents
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [41]:
# Find max
np.max(arr)

10

# **EXERCISES**

In [43]:
# Import NumPy as np
import numpy as np

In [45]:
# Create an array of 10 zeros
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [46]:
# Create an array of 10 ones
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [48]:
# Create an array of 10 fives
np.ones(10) * 5

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

In [51]:
# Create an array of 10 fives
np.zeros(10)+5

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

In [50]:
# Create an array of integers from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [53]:
# Create an array of even integers from 10 to 50
np.arange(10,51,2) # remember third argument sets the step

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [57]:
# Create a 3x3 matrix with values from 0 to 8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [59]:
# Create a 3x3 identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [65]:
# Generate random number between 0 and 1
np.random.rand(1)

array([ 0.63315878])

In [66]:
# Generate an array of 25 random numbers sampled from a standard normal distribution
np.random.randn(25)

array([-1.45311956,  0.8652471 ,  0.79174754,  0.55703206,  0.7635617 ,
        0.62971913,  2.03875829, -0.51596543, -0.78602945,  0.6526296 ,
       -0.05873997, -0.25578921,  3.24901856,  1.13603821, -0.69894458,
        0.10465106,  0.27068394, -2.03607074, -1.54990023, -0.9000141 ,
       -1.12030984, -0.18568582, -0.65149384, -1.12681111,  0.13257212])

In [73]:
# Generate matrix
np.arange(1,101).reshape(10,10)/100

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [70]:
# Generate matrix
np.linspace(0.01,1,100).reshape(10,10)

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [71]:
# Create an array of 20 linearly spaced points between 0 and 1
np.linspace(0,1,20)

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

In [76]:
# Create outputs
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [78]:
# Select bottom right corner
mat[2:,1:]


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [79]:
# Select the 20
mat[3,4]

20

In [88]:
# Grab chunk and create 3x1 matrix output with double brackets
mat[:3,1:2] # Slice everything up to but not including column index 2

array([[ 2],
       [ 7],
       [12]])

In [89]:
# Go to index 4 row and return everything
mat[4,:]

array([21, 22, 23, 24, 25])

In [92]:
# Return last row with negative indexing
mat[-1,:]

array([21, 22, 23, 24, 25])

In [91]:
# Grab all the columns of the last two rows with double bracket notation output
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [93]:
# Get sum of all the values in mat using universal function
mat.sum()

325

In [95]:
# Get sum of all the values in mat using sum function
np.sum(mat)

325

In [94]:
# Get standard deviation of the values in mat using universal function
mat.std()

7.2111025509279782

In [96]:
# Get standard deviation of the values in mat using standard deviation function
np.std(mat)

7.2111025509279782

In [98]:
# Get sum of all the columns in mat
mat.sum(axis=0)

array([55, 60, 65, 70, 75])